import React from 'react'
import styled from 'styled-components'

import { Heading1, List, Stack, Logo, Code, Button } from '../components'

const Link = styled.a`
  color: #0a84ae;
  text-decoration: none;
`

const clients = [
  {
    id: 'autogenerated-id-goes-here',
    name: 'Clients One',
    type: 'NO TYPE'
  },
  {
    id: 'beep-beep-boop-boop',
    name: 'Clients Two',
    type: 'SINGLE PAGE APPLICATION'
  }
]

class ClientList extends React.Component {
  render() {
    return (
      <div>
        <Heading1>Clients</Heading1>
        <div>Setup a mobile, web or IoT application to use Auth0 for Authentication.</div>
        <br />
        <br />
        <List>
          {clients.map(client => (
            <List.Item key={client.id}>
              <Logo />
              <div>
                <Link href={`/clients/${client.id}`}>{client.name}</Link>
                <div>{client.type}</div>
              </div>
              <div>
                Client Id: <Code>{client.id}</Code>
              </div>
              <Stack>
                <Button icon="copy" />
                <Button icon="copy" />
                <Button icon="copy" />
                <Button icon="copy" />
              </Stack>
            </List.Item>
          ))}
        </List>
      </div>
    )
  }
}

export default ClientList
