version: 2

jobs:
  "Run Unit Tests":
    working_directory: ~/cosmos
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install --force -g yarn@1.16'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-yarn-wee
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: yarn scripts test.ciunit
  "Run Integration Tests":
    working_directory: ~/cosmos
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install --force -g yarn@1.16'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-yarn-wee
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: yarn scripts test.ciintegration
  "Run Visual Tests":
    working_directory: ~/cosmos
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install --force -g yarn@1.16'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-yarn-wee
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: yarn scripts test.civisual
workflows:
  version: 2
  master:
    jobs:
      - "Run Unit Tests"
      - "Run Integration Tests"
      - "Run Visual Tests"
