version: 2
jobs:
  build:
    working_directory: ~/cosmos
    docker:
      - image: circleci/node:10.15.1
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g yarn@1.13'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-yarn-wee
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: yarn test