const colors = {
  base: {
    white: '#FFF',
    black: '#000',
    default: '#333',
    gray: '#979797',
    grayDark: '#636363',
    grayMedium: '#A8A8A8',
    grayLight: '#D9D9D9',
    grayLightest: '#F1F1F1',
    blue: '#0a84ae',
    blueLight: '#44c7f4',
    blueLightest: '#f5f7f9',
    orange: '#eb5424',
    orangeLighter: '#ff784d',
    orangeLightest: '#ffb299',
    green: '#4CD964',
    red: '#FF0000'
  },
  text: {
    default: '#212121',
    inputs: '#555',
    secondary: '#757575',
    subtle: '#BDBDBD',
    error: '#FF0000'
  },
  form: {
    title: '#000',
    divider: 'rgba(151,151,151,0.29)',
    background: '#f9f9f9'
  },
  input: {
    background: '#FFF',
    backgroundReadOnly: '#F3F4F4',
    border: '#D9D9D9',
    borderHover: '#B7B7B7',
    borderFocus: '#0a84ae',
    borderError: '#FF0000',
    icon: '#A2A2A2',
    text: '#333',
    placeholder: '#B2B2B2',
    placeholderDisabled: '#C1C1C1',
    placeholderReadOnly: '#333',
    label: '#333',
    labelDisabled: '#C6C6C6'
  },
  link: {
    default: '#0a84ae',
    defaultHover: '#0a84ae',
    defaultFocus: '#0a84ae',
    sidebar: '#333',
    sidebarHover: '#FF3E00',
    sidebarFocus: '#FF3E00'
  },
  tooltip: {
    background: '#1A1A1A',
    text: '#FFF'
  },
  tabs: {
    default: '#212121',
    defaultHover: '#0a84ae'
  },
  button: {
    defaultBackground: '#F1F1F1',
    defaultBackgroundHover: '#DAD9D9',
    defaultBackgroundFocus: '#A8A8A8',
    defaultText: '#333',
    defaultIcon: '#333',
    defaultBorder: '#F1F1F1',
    defaultBorderHover: '#DAD9D9',
    defaultBorderFocus: '#A8A8A8',
    primaryBackground: '#44c7f4',
    primaryBackgroundHover: '#14b9f1',
    primaryBackgroundFocus: '#14b9f1',
    primaryText: '#FFF',
    primaryIcon: '#FFF',
    primaryBorder: '#44c7f4',
    primaryBorderHover: '#14b9f1',
    primaryBorderFocus: '#14b9f1',
    primaryAltBackground: '#eb5424',
    primaryAltBackgroundHover: '#ca3f12',
    primaryAltBackgroundFocus: '#ca3f12',
    primaryAltText: '#FFF',
    primaryAltIcon: '#FFF',
    primaryAltBorder: '#eb5424',
    primaryAltBorderHover: '#ca3f12',
    primaryAltBorderFocus: '#ca3f12',
    transparentBackground: '#FFF',
    transparentBackgroundHover: '#F1F1F1',
    transparentBackgroundFocus: '#A8A8A8',
    transparentText: '#333',
    transparentIcon: '#333',
    transparentBorder: '#d0d2d3',
    transparentBorderHover: '#A8A8A8',
    transparentBorderFocus: '#333',
    disabledBackground: '#F1F1F1',
    disabledBackgroundHover: '#F1F1F1',
    disabledBackgroundFocus: '#F1F1F1',
    disabledText: '#A8A8A8',
    disabledIcon: '#A8A8A8',
    disabledBorder: '#F1F1F1',
    disabledBorderHover: '#F1F1F1',
    disabledBorderFocus: '#F1F1F1',
    destructiveBackground: '#FF0000',
    destructiveBackgroundHover: '#FF3434',
    destructiveBackgroundFocus: '#FF3434',
    destructiveText: '#FFF',
    destructiveIcon: '#FFF',
    destructiveBorder: '#FF0000',
    destructiveBorderHover: '#FF3434',
    destructiveBorderFocus: '#FF3434',
    successBackground: '#4CD964',
    successBackgroundHover: '#4CD964',
    successBackgroundFocus: '#4CD964',
    successText: '#FFF',
    successIcon: '#FFF',
    successBorder: '#4CD964',
    successBorderHover: '#4CD964',
    successBorderFocus: '#4CD964',
    linkText: '#0a84ae',
    linkIcon: '#0a84ae',
    linkHover: '#0a84ae',
    linkFocus: '#0a84ae'
  },
  icon: {
    default: '#333',
    light: '#A8A8A8'
  },
  list: {
    backgroundHover: '#FAFAFA',
    borderColor: '#DDD'
  }
}

export default colors
